/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class org_cps_umd_simulation_BCPSimulation */

#ifndef _Included_org_cps_umd_simulation_BCPSimulation
#define _Included_org_cps_umd_simulation_BCPSimulation
#ifdef __cplusplus
extern "C" {
#endif
/* Inaccessible static: STANDARD_CONSTRUCTOR */
/* Inaccessible static: class_00024org_00024cps_00024core_00024CPSComponent */
/* Inaccessible static: class_00024org_00024cps_00024core_00024CPSContainer */
/* Inaccessible static: class_00024org_00024cps_00024core_00024RootComponent */
/* Inaccessible static: class_00024org_00024cps_00024core_00024CPSComponent */
/* Inaccessible static: class_00024org_00024cps_00024core_00024Property */
/* Inaccessible static: class_00024org_00024cps_00024core_00024DataModel_00024DataCommand */
#undef org_cps_umd_simulation_BCPSimulation_DATA_PRIORITY
#define org_cps_umd_simulation_BCPSimulation_DATA_PRIORITY 2L
/* Inaccessible static: class_00024org_00024cps_00024core_00024Tree_00024Parent */
/* Inaccessible static: class_00024org_00024cps_00024data_00024ExpressionNode */
/*
 * Class:     org_cps_umd_simulation_BCPSimulation
 * Method:    close
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_org_cps_umd_simulation_BCPSimulation_close
  (JNIEnv *, jobject);

/*
 * Class:     org_cps_umd_simulation_BCPSimulation
 * Method:    save
 * Signature: (Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_org_cps_umd_simulation_BCPSimulation_save
  (JNIEnv *, jobject, jstring);

/*
 * Class:     org_cps_umd_simulation_BCPSimulation
 * Method:    load
 * Signature: (Ljava/lang/String;)I
 */
JNIEXPORT jint JNICALL Java_org_cps_umd_simulation_BCPSimulation_load
  (JNIEnv *, jobject, jstring);

/*
 * Class:     org_cps_umd_simulation_BCPSimulation
 * Method:    call
 * Signature: (I[D)I
 */
JNIEXPORT jint JNICALL Java_org_cps_umd_simulation_BCPSimulation_call
  (JNIEnv *, jobject, jint, jdoubleArray);

/*
 * Class:     org_cps_umd_simulation_BCPSimulation
 * Method:    abort
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_org_cps_umd_simulation_BCPSimulation_abort
  (JNIEnv *, jobject);

/*
 * Class:     org_cps_umd_simulation_BCPSimulation
 * Method:    calculateStep
 * Signature: (F)I
 */
JNIEXPORT jint JNICALL Java_org_cps_umd_simulation_BCPSimulation_calculateStep
  (JNIEnv *, jobject, jfloat);

/*
 * Class:     org_cps_umd_simulation_BCPSimulation
 * Method:    link
 * Signature: (Lorg/cps/umd/simulation/SimulationDisplayData;Lorg/cps/umd/simulation/SimulationParameterData;Lorg/cps/umd/simulation/SimulationInputParameterData;Lorg/cps/umd/simulation/SimulationTypeData;)V
 */
JNIEXPORT void JNICALL Java_org_cps_umd_simulation_BCPSimulation_link
  (JNIEnv *, jobject, jobject, jobject, jobject, jobject);

/*
 * Class:     org_cps_umd_simulation_BCPSimulation
 * Method:    unlink
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_org_cps_umd_simulation_BCPSimulation_unlink
  (JNIEnv *, jobject);

/*
 * Class:     org_cps_umd_simulation_BCPSimulation
 * Method:    getInstantTime
 * Signature: ()F
 */
JNIEXPORT jfloat JNICALL Java_org_cps_umd_simulation_BCPSimulation_getInstantTime
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
